- name: Create Branch
  # You may pin to the exact commit or the version.
  # uses: peterjgrainger/action-create-branch@b48b0ca0e307c9b56f059b70274984ffeaa90a43
  uses: peterjgrainger/action-create-branch@v2.0.1
  with:
    # The branch to create
    branch: 'release-candidate'
