name: Crear una rama
on:
  push:
    branches: [main]
jobs:
  job1:
    name: Rama
    runs-on: ubuntu-latest
    steps:
    - name: Create branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The branch to create
        branch: 'release-candidate'
